Update build workflows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,12 @@ on:
       - '*.properties'
   pull_request:
   workflow_dispatch:
+    inputs:
+      release:
+        description: 'Release'
+        type: boolean
+        required: true
+        default: false
 
 jobs:
   build:
@@ -26,22 +32,52 @@ jobs:
           distribution: 'temurin'
           java-version: 17
 
-      - name: Cache
-        uses: actions/cache@v4
+      - name: Setup Gradle
+        uses: gradle/actions/setup-gradle@v3
+
+      - name: Set environments
+        run: |
+          {
+            echo "version=v$(grep -oP 'versionName\s*=\s*\"\K[^\"]+' app/build.gradle.kts)"
+            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
+            echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
+          } >> $GITHUB_ENV
+
+      - name: Get previous version name
+        uses: oprypin/find-latest-tag@v1.1.2
+        if: github.event.inputs.release == 'true'
+        id: previous
         with:
-          path: |
-            ~/.gradle/caches/
-            ~/.gradle/wrapper/
-            ./.gradle/
-          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
+          repository: ${{ github.repository }}
+          releases-only: true
+
+      - name: Release check
+        if: github.event.inputs.release == 'true'
+        run: |
+          if [ "${{ steps.previous.outputs.tag }}" == "${{ env.version }}" ]; then
+            echo -e "\nERROR!\nThe same tag already exists!\n"
+            echo "Please change versionName in build.gradle"
+            echo ""
+            exit 1
+          fi
 
       - name: Build with Gradle
         run: |
-          ./gradlew assemble --no-daemon
-          {
-            echo "version=v$(grep versionName app/build.gradle.kts | awk '{print $3}' | tr -d \")"
-            echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
-          } >> "$GITHUB_ENV"
+          if [ "${{ secrets.STORE_FILE }}" == "" ]; then
+            echo -e "\nERROR!\nTo release, you need to set up a signing key!\n"
+            echo "STORE_FILE: A Base64 encoded string of the signing key in JKS format"
+            echo "STORE_PASSWORD: Key store password"
+            echo "KEY_ALIAS: Key alias"
+            echo "KEY_PASSWORD: Key password"
+            echo ""
+            exit 1
+          else
+            echo "${{ secrets.STORE_FILE }}" | base64 -d > app/release.jks
+            export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
+            export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
+            export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
+          fi
+          ./gradlew assemble --no-daemon --stacktrace
 
       - name: Upload APK
         uses: actions/upload-artifact@v4
